# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from rpcz import service
from rpcz import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import check_grasp_reachability_pb2
import geometry_msgs_pb2
import grasp_pb2


_CHECKGRASPREACHABILITYSERVICE = descriptor.ServiceDescriptor(
  name='CheckGraspReachabilityService',
  full_name='graspit_rpcz.CheckGraspReachabilityService',
  file=check_grasp_reachability_pb2.DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=227,
  serialized_end=356,
  methods=[
  descriptor.MethodDescriptor(
    name='run',
    full_name='graspit_rpcz.CheckGraspReachabilityService.run',
    index=0,
    containing_service=None,
    input_type=check_grasp_reachability_pb2._CHECKGRASPREACHABILITYREQUEST,
    output_type=check_grasp_reachability_pb2._CHECKGRASPREACHABILITYRESPONSE,
    options=None,
  ),
])

class CheckGraspReachabilityService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _CHECKGRASPREACHABILITYSERVICE
class CheckGraspReachabilityService_Stub(CheckGraspReachabilityService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _CHECKGRASPREACHABILITYSERVICE

