# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: check_grasp_reachability.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import geometry_msgs_pb2
import grasp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='check_grasp_reachability.proto',
  package='graspit_rpcz',
  serialized_pb='\n\x1e\x63heck_grasp_reachability.proto\x12\x0cgraspit_rpcz\x1a\x13geometry_msgs.proto\x1a\x0bgrasp.proto\"F\n\x1d\x43heckGraspReachabilityRequest\x12%\n\x05grasp\x18\x01 \x02(\x0b\x32\x16.graspit_rpcz.GraspMsg\"F\n\x1e\x43heckGraspReachabilityResponse\x12\x0f\n\x07graspId\x18\x01 \x02(\x05\x12\x13\n\x0bgraspStatus\x18\x02 \x02(\x05\x32\x81\x01\n\x1d\x43heckGraspReachabilityService\x12`\n\x03run\x12+.graspit_rpcz.CheckGraspReachabilityRequest\x1a,.graspit_rpcz.CheckGraspReachabilityResponse')




_CHECKGRASPREACHABILITYREQUEST = _descriptor.Descriptor(
  name='CheckGraspReachabilityRequest',
  full_name='graspit_rpcz.CheckGraspReachabilityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grasp', full_name='graspit_rpcz.CheckGraspReachabilityRequest.grasp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=152,
)


_CHECKGRASPREACHABILITYRESPONSE = _descriptor.Descriptor(
  name='CheckGraspReachabilityResponse',
  full_name='graspit_rpcz.CheckGraspReachabilityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graspId', full_name='graspit_rpcz.CheckGraspReachabilityResponse.graspId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='graspStatus', full_name='graspit_rpcz.CheckGraspReachabilityResponse.graspStatus', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=154,
  serialized_end=224,
)

_CHECKGRASPREACHABILITYREQUEST.fields_by_name['grasp'].message_type = grasp_pb2._GRASPMSG
DESCRIPTOR.message_types_by_name['CheckGraspReachabilityRequest'] = _CHECKGRASPREACHABILITYREQUEST
DESCRIPTOR.message_types_by_name['CheckGraspReachabilityResponse'] = _CHECKGRASPREACHABILITYRESPONSE

class CheckGraspReachabilityRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKGRASPREACHABILITYREQUEST

  # @@protoc_insertion_point(class_scope:graspit_rpcz.CheckGraspReachabilityRequest)

class CheckGraspReachabilityResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKGRASPREACHABILITYRESPONSE

  # @@protoc_insertion_point(class_scope:graspit_rpcz.CheckGraspReachabilityResponse)


# @@protoc_insertion_point(module_scope)
