# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compressed_image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='compressed_image.proto',
  package='',
  serialized_pb='\n\x16\x63ompressed_image.proto\"/\n\x0f\x43ompressedImage\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c')




_COMPRESSEDIMAGE = _descriptor.Descriptor(
  name='CompressedImage',
  full_name='CompressedImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='CompressedImage.format', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='CompressedImage.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['CompressedImage'] = _COMPRESSEDIMAGE

class CompressedImage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMPRESSEDIMAGE

  # @@protoc_insertion_point(class_scope:CompressedImage)


# @@protoc_insertion_point(module_scope)
