# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from rpcz import service
from rpcz import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import execute_grasp_pb2
import grasp_pb2


_EXECUTEGRASPSERVICE = descriptor.ServiceDescriptor(
  name='ExecuteGraspService',
  full_name='graspit_rpcz.ExecuteGraspService',
  file=execute_grasp_pb2.DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=176,
  serialized_end=275,
  methods=[
  descriptor.MethodDescriptor(
    name='run',
    full_name='graspit_rpcz.ExecuteGraspService.run',
    index=0,
    containing_service=None,
    input_type=execute_grasp_pb2._EXECUTEGRASPREQUEST,
    output_type=execute_grasp_pb2._EXECUTEGRASPRESPONSE,
    options=None,
  ),
])

class ExecuteGraspService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _EXECUTEGRASPSERVICE
class ExecuteGraspService_Stub(ExecuteGraspService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _EXECUTEGRASPSERVICE

