# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from rpcz import service
from rpcz import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import get_option_selection_pb2
import image_pb2
import compressed_image_pb2


_GETOPTIONSELECTIONSERVICE = descriptor.ServiceDescriptor(
  name='GetOptionSelectionService',
  full_name='graspit_rpcz.GetOptionSelectionService',
  file=get_option_selection_pb2.DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=912,
  serialized_end=1029,
  methods=[
  descriptor.MethodDescriptor(
    name='run',
    full_name='graspit_rpcz.GetOptionSelectionService.run',
    index=0,
    containing_service=None,
    input_type=get_option_selection_pb2._GETOPTIONSELECTIONREQUEST,
    output_type=get_option_selection_pb2._GETOPTIONSELECTIONRESPONSE,
    options=None,
  ),
])

class GetOptionSelectionService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _GETOPTIONSELECTIONSERVICE
class GetOptionSelectionService_Stub(GetOptionSelectionService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _GETOPTIONSELECTIONSERVICE

