# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from rpcz import service
from rpcz import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import get_camera_origin_pb2
import geometry_msgs_pb2


_CAMERAORIGINSERVICE = descriptor.ServiceDescriptor(
  name='CameraOriginService',
  full_name='graspit_rpcz.CameraOriginService',
  file=get_camera_origin_pb2.DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=138,
  serialized_end=237,
  methods=[
  descriptor.MethodDescriptor(
    name='run',
    full_name='graspit_rpcz.CameraOriginService.run',
    index=0,
    containing_service=None,
    input_type=get_camera_origin_pb2._CAMERAORIGINREQUEST,
    output_type=get_camera_origin_pb2._CAMERAORIGINRESPONSE,
    options=None,
  ),
])

class CameraOriginService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _CAMERAORIGINSERVICE
class CameraOriginService_Stub(CameraOriginService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _CAMERAORIGINSERVICE

