# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_option_selection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import image_pb2
import compressed_image_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_option_selection.proto',
  package='graspit_rpcz',
  serialized_pb='\n\x1aget_option_selection.proto\x12\x0cgraspit_rpcz\x1a\x0bimage.proto\x1a\x16\x63ompressed_image.proto\"\xc7\x05\n\x19GetOptionSelectionRequest\x12I\n\x0cimageOptions\x18\x01 \x03(\x0b\x32\x33.graspit_rpcz.GetOptionSelectionRequest.ImageOption\x12]\n\x16\x63ompressedImageOptions\x18\x02 \x03(\x0b\x32=.graspit_rpcz.GetOptionSelectionRequest.CompressedImageOption\x12\x15\n\rstringOptions\x18\x03 \x03(\t\x12!\n\x16minimumConfidenceLevel\x18\x04 \x02(\x02:\x01\x30\x1a\x45\n\x11OptionDescription\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0f\n\x04\x63ost\x18\x02 \x02(\x02:\x01\x30\x12\n\n\x02id\x18\x03 \x01(\x05\x1a\x82\x01\n\x0bImageOption\x12#\n\x06option\x18\x01 \x02(\x0b\x32\x13.graspit_rpcz.Image\x12N\n\x0b\x64\x65scription\x18\x02 \x02(\x0b\x32\x39.graspit_rpcz.GetOptionSelectionRequest.OptionDescription\x1a\x89\x01\n\x15\x43ompressedImageOption\x12 \n\x06option\x18\x01 \x02(\x0b\x32\x10.CompressedImage\x12N\n\x0b\x64\x65scription\x18\x02 \x02(\x0b\x32\x39.graspit_rpcz.GetOptionSelectionRequest.OptionDescription\x1an\n\x0cStringOption\x12\x0e\n\x06option\x18\x01 \x02(\t\x12N\n\x0b\x64\x65scription\x18\x02 \x02(\x0b\x32\x39.graspit_rpcz.GetOptionSelectionRequest.OptionDescription\"s\n\x1aGetOptionSelectionResponse\x12\x16\n\x0eselectedOption\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x02(\x02\x12\x15\n\rinterestLevel\x18\x03 \x03(\x02\x12\x12\n\noption_ids\x18\x04 \x03(\x05\x32u\n\x19GetOptionSelectionService\x12X\n\x03run\x12\'.graspit_rpcz.GetOptionSelectionRequest\x1a(.graspit_rpcz.GetOptionSelectionResponse')




_GETOPTIONSELECTIONREQUEST_OPTIONDESCRIPTION = _descriptor.Descriptor(
  name='OptionDescription',
  full_name='graspit_rpcz.GetOptionSelectionRequest.OptionDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='graspit_rpcz.GetOptionSelectionRequest.OptionDescription.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='graspit_rpcz.GetOptionSelectionRequest.OptionDescription.cost', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='graspit_rpcz.GetOptionSelectionRequest.OptionDescription.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=339,
  serialized_end=408,
)

_GETOPTIONSELECTIONREQUEST_IMAGEOPTION = _descriptor.Descriptor(
  name='ImageOption',
  full_name='graspit_rpcz.GetOptionSelectionRequest.ImageOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='option', full_name='graspit_rpcz.GetOptionSelectionRequest.ImageOption.option', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='graspit_rpcz.GetOptionSelectionRequest.ImageOption.description', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=411,
  serialized_end=541,
)

_GETOPTIONSELECTIONREQUEST_COMPRESSEDIMAGEOPTION = _descriptor.Descriptor(
  name='CompressedImageOption',
  full_name='graspit_rpcz.GetOptionSelectionRequest.CompressedImageOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='option', full_name='graspit_rpcz.GetOptionSelectionRequest.CompressedImageOption.option', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='graspit_rpcz.GetOptionSelectionRequest.CompressedImageOption.description', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=544,
  serialized_end=681,
)

_GETOPTIONSELECTIONREQUEST_STRINGOPTION = _descriptor.Descriptor(
  name='StringOption',
  full_name='graspit_rpcz.GetOptionSelectionRequest.StringOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='option', full_name='graspit_rpcz.GetOptionSelectionRequest.StringOption.option', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='graspit_rpcz.GetOptionSelectionRequest.StringOption.description', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=683,
  serialized_end=793,
)

_GETOPTIONSELECTIONREQUEST = _descriptor.Descriptor(
  name='GetOptionSelectionRequest',
  full_name='graspit_rpcz.GetOptionSelectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageOptions', full_name='graspit_rpcz.GetOptionSelectionRequest.imageOptions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compressedImageOptions', full_name='graspit_rpcz.GetOptionSelectionRequest.compressedImageOptions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stringOptions', full_name='graspit_rpcz.GetOptionSelectionRequest.stringOptions', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimumConfidenceLevel', full_name='graspit_rpcz.GetOptionSelectionRequest.minimumConfidenceLevel', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETOPTIONSELECTIONREQUEST_OPTIONDESCRIPTION, _GETOPTIONSELECTIONREQUEST_IMAGEOPTION, _GETOPTIONSELECTIONREQUEST_COMPRESSEDIMAGEOPTION, _GETOPTIONSELECTIONREQUEST_STRINGOPTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=793,
)


_GETOPTIONSELECTIONRESPONSE = _descriptor.Descriptor(
  name='GetOptionSelectionResponse',
  full_name='graspit_rpcz.GetOptionSelectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selectedOption', full_name='graspit_rpcz.GetOptionSelectionResponse.selectedOption', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='graspit_rpcz.GetOptionSelectionResponse.confidence', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interestLevel', full_name='graspit_rpcz.GetOptionSelectionResponse.interestLevel', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='option_ids', full_name='graspit_rpcz.GetOptionSelectionResponse.option_ids', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=795,
  serialized_end=910,
)

_GETOPTIONSELECTIONREQUEST_OPTIONDESCRIPTION.containing_type = _GETOPTIONSELECTIONREQUEST;
_GETOPTIONSELECTIONREQUEST_IMAGEOPTION.fields_by_name['option'].message_type = image_pb2._IMAGE
_GETOPTIONSELECTIONREQUEST_IMAGEOPTION.fields_by_name['description'].message_type = _GETOPTIONSELECTIONREQUEST_OPTIONDESCRIPTION
_GETOPTIONSELECTIONREQUEST_IMAGEOPTION.containing_type = _GETOPTIONSELECTIONREQUEST;
_GETOPTIONSELECTIONREQUEST_COMPRESSEDIMAGEOPTION.fields_by_name['option'].message_type = compressed_image_pb2._COMPRESSEDIMAGE
_GETOPTIONSELECTIONREQUEST_COMPRESSEDIMAGEOPTION.fields_by_name['description'].message_type = _GETOPTIONSELECTIONREQUEST_OPTIONDESCRIPTION
_GETOPTIONSELECTIONREQUEST_COMPRESSEDIMAGEOPTION.containing_type = _GETOPTIONSELECTIONREQUEST;
_GETOPTIONSELECTIONREQUEST_STRINGOPTION.fields_by_name['description'].message_type = _GETOPTIONSELECTIONREQUEST_OPTIONDESCRIPTION
_GETOPTIONSELECTIONREQUEST_STRINGOPTION.containing_type = _GETOPTIONSELECTIONREQUEST;
_GETOPTIONSELECTIONREQUEST.fields_by_name['imageOptions'].message_type = _GETOPTIONSELECTIONREQUEST_IMAGEOPTION
_GETOPTIONSELECTIONREQUEST.fields_by_name['compressedImageOptions'].message_type = _GETOPTIONSELECTIONREQUEST_COMPRESSEDIMAGEOPTION
DESCRIPTOR.message_types_by_name['GetOptionSelectionRequest'] = _GETOPTIONSELECTIONREQUEST
DESCRIPTOR.message_types_by_name['GetOptionSelectionResponse'] = _GETOPTIONSELECTIONRESPONSE

class GetOptionSelectionRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class OptionDescription(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _GETOPTIONSELECTIONREQUEST_OPTIONDESCRIPTION

    # @@protoc_insertion_point(class_scope:graspit_rpcz.GetOptionSelectionRequest.OptionDescription)

  class ImageOption(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _GETOPTIONSELECTIONREQUEST_IMAGEOPTION

    # @@protoc_insertion_point(class_scope:graspit_rpcz.GetOptionSelectionRequest.ImageOption)

  class CompressedImageOption(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _GETOPTIONSELECTIONREQUEST_COMPRESSEDIMAGEOPTION

    # @@protoc_insertion_point(class_scope:graspit_rpcz.GetOptionSelectionRequest.CompressedImageOption)

  class StringOption(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _GETOPTIONSELECTIONREQUEST_STRINGOPTION

    # @@protoc_insertion_point(class_scope:graspit_rpcz.GetOptionSelectionRequest.StringOption)
  DESCRIPTOR = _GETOPTIONSELECTIONREQUEST

  # @@protoc_insertion_point(class_scope:graspit_rpcz.GetOptionSelectionRequest)

class GetOptionSelectionResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETOPTIONSELECTIONRESPONSE

  # @@protoc_insertion_point(class_scope:graspit_rpcz.GetOptionSelectionResponse)


# @@protoc_insertion_point(module_scope)
