# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grasp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import graspable_object_pb2
import geometry_msgs_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grasp.proto',
  package='graspit_rpcz',
  serialized_pb='\n\x0bgrasp.proto\x12\x0cgraspit_rpcz\x1a\x16graspable_object.proto\x1a\x13geometry_msgs.proto\":\n\x0cHandStateMsg\x12\x18\n\thand_pose\x18\x01 \x02(\x0b\x32\x05.Pose\x12\x10\n\x08hand_dof\x18\x02 \x03(\x02\"\x81\x02\n\x08GraspMsg\x12\x0f\n\x07graspId\x18\x07 \x02(\x05\x12 \n\x06object\x18\x01 \x02(\x0b\x32\x10.GraspableObject\x12\x17\n\x0f\x65psilon_quality\x18\x02 \x02(\x02\x12\x16\n\x0evolume_quality\x18\x03 \x02(\x02\x12\x1b\n\x13secondary_qualities\x18\x04 \x03(\x02\x12\x38\n\x14pre_grasp_hand_state\x18\x05 \x02(\x0b\x32\x1a.graspit_rpcz.HandStateMsg\x12:\n\x16\x66inal_grasp_hand_state\x18\x06 \x02(\x0b\x32\x1a.graspit_rpcz.HandStateMsg')




_HANDSTATEMSG = _descriptor.Descriptor(
  name='HandStateMsg',
  full_name='graspit_rpcz.HandStateMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hand_pose', full_name='graspit_rpcz.HandStateMsg.hand_pose', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hand_dof', full_name='graspit_rpcz.HandStateMsg.hand_dof', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=132,
)


_GRASPMSG = _descriptor.Descriptor(
  name='GraspMsg',
  full_name='graspit_rpcz.GraspMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graspId', full_name='graspit_rpcz.GraspMsg.graspId', index=0,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object', full_name='graspit_rpcz.GraspMsg.object', index=1,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epsilon_quality', full_name='graspit_rpcz.GraspMsg.epsilon_quality', index=2,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume_quality', full_name='graspit_rpcz.GraspMsg.volume_quality', index=3,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secondary_qualities', full_name='graspit_rpcz.GraspMsg.secondary_qualities', index=4,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pre_grasp_hand_state', full_name='graspit_rpcz.GraspMsg.pre_grasp_hand_state', index=5,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final_grasp_hand_state', full_name='graspit_rpcz.GraspMsg.final_grasp_hand_state', index=6,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=135,
  serialized_end=392,
)

_HANDSTATEMSG.fields_by_name['hand_pose'].message_type = geometry_msgs_pb2._POSE
_GRASPMSG.fields_by_name['object'].message_type = graspable_object_pb2._GRASPABLEOBJECT
_GRASPMSG.fields_by_name['pre_grasp_hand_state'].message_type = _HANDSTATEMSG
_GRASPMSG.fields_by_name['final_grasp_hand_state'].message_type = _HANDSTATEMSG
DESCRIPTOR.message_types_by_name['HandStateMsg'] = _HANDSTATEMSG
DESCRIPTOR.message_types_by_name['GraspMsg'] = _GRASPMSG

class HandStateMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HANDSTATEMSG

  # @@protoc_insertion_point(class_scope:graspit_rpcz.HandStateMsg)

class GraspMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GRASPMSG

  # @@protoc_insertion_point(class_scope:graspit_rpcz.GraspMsg)


# @@protoc_insertion_point(module_scope)
