# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graspable_object.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import geometry_msgs_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='graspable_object.proto',
  package='',
  serialized_pb='\n\x16graspable_object.proto\x1a\x13geometry_msgs.proto\"C\n\x0fGraspableObject\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05model\x18\x02 \x02(\t\x12\x13\n\x04pose\x18\x03 \x02(\x0b\x32\x05.Pose')




_GRASPABLEOBJECT = _descriptor.Descriptor(
  name='GraspableObject',
  full_name='GraspableObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GraspableObject.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='GraspableObject.model', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='GraspableObject.pose', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=114,
)

_GRASPABLEOBJECT.fields_by_name['pose'].message_type = geometry_msgs_pb2._POSE
DESCRIPTOR.message_types_by_name['GraspableObject'] = _GRASPABLEOBJECT

class GraspableObject(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GRASPABLEOBJECT

  # @@protoc_insertion_point(class_scope:GraspableObject)


# @@protoc_insertion_point(module_scope)
