# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from rpcz import service
from rpcz import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import image_pb2

