# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='graspit_rpcz',
  serialized_pb='\n\x0bimage.proto\x12\x0cgraspit_rpcz\"\xce\x03\n\x05Image\x12\r\n\x05width\x18\x01 \x02(\r\x12\x0e\n\x06height\x18\x02 \x02(\r\x12\x35\n\x0cpixel_format\x18\x03 \x02(\x0e\x32\x1f.graspit_rpcz.Image.PixelFormat\x12\x0c\n\x04step\x18\x04 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x02(\x0c\"\xd2\x02\n\x0bPixelFormat\x12\x18\n\x14UNKNOWN_PIXEL_FORMAT\x10\x00\x12\n\n\x06L_INT8\x10\x01\x12\x0b\n\x07L_INT16\x10\x02\x12\x0c\n\x08RGB_INT8\x10\x03\x12\r\n\tRGBA_INT8\x10\x04\x12\r\n\tBGRA_INT8\x10\x05\x12\r\n\tRGB_INT16\x10\x06\x12\r\n\tRGB_INT32\x10\x07\x12\x0c\n\x08\x42GR_INT8\x10\x08\x12\r\n\tBGR_INT16\x10\t\x12\r\n\tBGR_INT32\x10\n\x12\r\n\tR_FLOAT16\x10\x0b\x12\x0f\n\x0bRGB_FLOAT16\x10\x0c\x12\r\n\tR_FLOAT32\x10\r\x12\x0f\n\x0bRGB_FLOAT32\x10\x0e\x12\x0f\n\x0b\x42\x41YER_RGGB8\x10\x0f\x12\x0f\n\x0b\x42\x41YER_RGGR8\x10\x10\x12\x0f\n\x0b\x42\x41YER_GBRG8\x10\x11\x12\x0f\n\x0b\x42\x41YER_GRBG8\x10\x12\x12\x16\n\x12PIXEL_FORMAT_COUNT\x10\x13')



_IMAGE_PIXELFORMAT = _descriptor.EnumDescriptor(
  name='PixelFormat',
  full_name='graspit_rpcz.Image.PixelFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_PIXEL_FORMAT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='L_INT8', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='L_INT16', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB_INT8', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGBA_INT8', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGRA_INT8', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB_INT16', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB_INT32', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGR_INT8', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGR_INT16', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGR_INT32', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='R_FLOAT16', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB_FLOAT16', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='R_FLOAT32', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB_FLOAT32', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAYER_RGGB8', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAYER_RGGR8', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAYER_GBRG8', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAYER_GRBG8', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PIXEL_FORMAT_COUNT', index=19, number=19,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=154,
  serialized_end=492,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='graspit_rpcz.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='graspit_rpcz.Image.width', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='graspit_rpcz.Image.height', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pixel_format', full_name='graspit_rpcz.Image.pixel_format', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step', full_name='graspit_rpcz.Image.step', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='graspit_rpcz.Image.data', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMAGE_PIXELFORMAT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=492,
)

_IMAGE.fields_by_name['pixel_format'].enum_type = _IMAGE_PIXELFORMAT
_IMAGE_PIXELFORMAT.containing_type = _IMAGE;
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE

class Image(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IMAGE

  # @@protoc_insertion_point(class_scope:graspit_rpcz.Image)


# @@protoc_insertion_point(module_scope)
